image: gradle:alpine


variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test_build:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle


run_tests: 
  stage: test 
  script: gradle clean test 
  cache: 
     key: "$CI_COMMIT_REF_NAME"
     policy: pull
     paths:
      - build
      - .gradle


